site_name: DevOps Notes
site_author: Yoad Duani
repo_url: https://github.com/Yoad-Duani/personal_notes
repo_name: DevOps Notes

theme:
  name: material
  features:
    # - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    # - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: darkblue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: darkblue
      accent: lime

nav:
  - Overview: ./index.md
  - Linux:
      - ./linux/startup-ubuntu.md
  - Git & GitHub:
      - ./git/understanding-git-merge.md
      - ./git/understanding-git-stash.md
  - Databases:
      - Vertica:
          - ./dbs/vertica/vertica.md
      - Mysql:
          - ./dbs/mysql/mysql.md
      - Mongodb:
          - ./dbs/mongodb/mongo.md
  - Cloud:
      - GCP:
          - ./cloud/gcp/networking.md
          - ./cloud/gcp/gcloud.md
      - AWS:
          - ./cloud/aws/aws.cli.md
  - Kubernets:
      - ./kubernetes/kubectl.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Yoad-Duani
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yoad-duani

copyright: |
  &copy; 2024 <a href="https://github.com/Yoad-Duani"  target="_blank" rel="noopener">Yoad Duani</a>
